### ISSUE TITLE
Separate throttling control for remote and local replication  

### ISSUE THREAD

**Issue by xunyin8** [linkedin/ambry#1055]
Currently, `replication.replica.thread.throttle.sleep.duration.ms` is the same for both remote and local replication. One way to improve the throttling mechanism is to have different sleep duration for remote and local replication threads. Favoring (less sleep duration) local over remote replication will yield better results.

**Comment by vgkholla** [comment]
Slight correction on this - what we need is for different backoff configuration for "replication.replica.thread.throttle.sleep.duration.ms" (not the synced backoff for now)

**Comment by vgkholla** [comment]
An additional "feature" that this unlocks is that setting values for inter > intra also allows for a coarse way of preferring local replication over remote
