### ISSUE TITLE
有realse版本吗？

### ISSUE THREAD

**Issue by adonis2014** [linkedin/ambry#1132]
想在项目中使用，没有realse版本？
(Translated by Yingyi)  "I am considering employing Ambry for my project, is there any release version to use?"

**Comment by jsjtzyy** [comment]
Hey @adonis2014, the master branch is the version currently deployed in production (LinkedIn Corporation). We keep maintaining and updating the master branch. All features have been verified in our production. There is temporarily no specific version to release. Let us know if you have more concerns or suggestions. Thanks!

**Comment by adonis2014** [comment]
Thank you for reply。
