### ISSUE TITLE
Make account/container optional in NettyPerfClient

### ISSUE THREAD

**Issue by zzmao** [linkedin/ambry#1438]
For current open source version ambry with `InMemoryAccountService`, we can't provide account/container header in PUT request. 
If `ambry-unknown-account`  is provided, it fails in `accountAndContainerSanityCheck`.
If something else provided, it will fail in ensureAccountNameMatch (edited) 

To use NettyPerfClient and issue PUT requests to open sources frontend. We need first make `targetAccountName` and `targetContainerName` optional. 

For example: 

```
java -Dlog4j.configuration=file:../config/log4j.properties -cp ambry.jar com.github.ambry.tools.perf.rest.NettyPerfClient --hosts localhost  --port 1174 --requestType POST --concurrency 1 --postBlobTotalSize 100 --postBlobChunkSize 100 
```

**Comment by jsjtzyy** [comment]
Close this issue as #1441  is merged.
