### ISSUE TITLE
LocalNetworkClient: avoid serializing/deserializing request/response objects and add test

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#1442]
There is currently a todo to avoid serializing and deserializing request and response objects in the cloud router. With some changes to LocalNetworkClient and some refactoring of AmbryRequests, it should be possible to pass the java request object as is without serializing.

Avoiding serde on the response path may take some additional changes in the router, since currently ResponseInfo currently just wraps a buffer that is deserialized in the router code.

LocalNetworkClient/LocalRequestResponseChannel could also use a unit test. Currently they are tested via the router package tests.

**Comment by marcluque** [comment]
Hey there, I would like to work on this if this is still wanted/relevant. 

In case this is still relevant: could you point me to where exactly the serialization/deserialization happens? I have found this [todo](https://github.com/linkedin/ambry/blob/03139f1740f81b5e55c05860e2e2b24410d86d33/ambry-network/src/main/java/com/github/ambry/network/LocalNetworkClient.java#L81) that I suppose is the one you were talking about. But I'm not sure I see the inefficient part here. Are you referring to the fact that when slicing the header off, the payload is put in a new buffer? Maybe I'm misunderstanding something, I'd appreciate if you could elaborate a little on this matter.

Thank you in advance for your time.
