### ISSUE TITLE
Wrong URL in README

### ISSUE THREAD

**Issue by liotev** [linkedin/ambry#1708]
In the README file, under section "Research", the URL of the "Paper introducing Ambry"  (http://dprg.cs.uiuc.edu/docs/SIGMOD2016-a/ambry.pdf) is not correct: clicking on it shows a "Not Found" page.

**Comment by jsjtzyy** [comment]
Hi @liotev  try this: https://assured-cloud-computing.illinois.edu/files/2014/03/Ambry-LinkedIns-Scalable-GeoDistributed-Object-Store.pdf

**Comment by djKooks** [comment]
@jsjtzyy @liotev seems already known issue but haven't been updated for several month, so created a PR 🙏
