### ISSUE TITLE
Make selector connect() non-blocking for SSL connections

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#297]
Currently, for connections over SSL, the ambry selector returns an established connection after a poll even before the handshake is completed. This is not very useful as the caller will then have to repeatedly check outside of the selector poll on whether the handshake is complete, which is not ideal.

Instead, let the selector do the work as part of the poll. The selector should only return a connection after the connection is established *and* the handshake is complete. If the handshake does not complete for any reason, then it should be treated as a connection establishment failure. This way the callers of the selector can be agnostic to SSL, and can interact with the selector in a completely non-blocking way.

**Comment by nsivabalan** [comment]
https://github.com/linkedin/ambry/pull/310
