### ISSUE TITLE
NFS or HDFS

### ISSUE THREAD

**Issue by gaurav46** [linkedin/ambry#311]
Does ambry support NFS or HDFS for storage?

**Comment by vgkholla** [comment]
Yes, Ambry just relies on the mount paths provided in the cluster map files. These mount paths can point to any sort of storage (local, NFS, HDFS). We haven't evaluated performance on network disks however.

Also, ambrydev@googlegroups.com would be a good place to have this discussion (we just realized that non-members could not post and have fixed it).

**Comment by tlossen** [comment]
@vgkholla hmmm, where is the group page for ambrydev@googlegroups.com ? i cannot seem to find it. maybe it is not indexed / searchable?

**Comment by pnarayanan** [comment]
@tlossen could you try https://groups.google.com/forum/#!forum/ambrydev
will look into why it does not show up in search.

**Comment by tlossen** [comment]
excellent, thanks.
