### ISSUE TITLE
Refactor ResponseHandler responsible for Failure Detection

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#312]
`ResponseHandler` class which is responsible for failure detection may be refactored to make it a bit more intuitive without changing the core implementation (which works just fine). We should do this after all the router changes are in.

**Comment by vgkholla** [comment]
Just a note on what is probably meant by more intuitive here. There are a couple of places in the `NonBlockingRouter` related code where is how the `ResponseHandler` is used
```
responseHandler.onRequestResponseException(getRequestInfo.replicaId, new IOException("NetworkClient error"));
```
which clearly indicates that the caller knows the implementation of `onRequestResponseException()` and that it is looking for `IOException`. This should not be the case.

Clearer acceptance criteria should be available once the router changes are completed as @pnarayanan  indicated.

**Comment by pnarayanan** [comment]
@vgkholla the example you quoted does not make an assumption about the implementation actually. The problem is that `ResponseHandler` only has two apis for notification. One that takes a `ServerErrorCode` and the other that takes an `Exception`. 
In the context of the quoted call above, the error is not a `ServerErrorCode`, so one has to use the api that takes the `Exception` to notify. Given that this is a `NetworkClient` related error, `IOException` is the most appropriate exception to use - but there are no assumptions made about the implementation of the `ResponseHandler`.

What we want here is to make the class more flexible. At the time this was written, all errors were `ServerErrorCode`s (those from the coordinator).

**Comment by vgkholla** [comment]
@pnarayanan did the PR referenced above resolve this issue as stated?

**Comment by pnarayanan** [comment]
Yes, this can be closed.
