### ISSUE TITLE
Make the Protocol and MessageFormat deal with ByteBuffers instead of InputStream

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#313]
The protocol (`PutRequest` and `GetRequest`) and MessageFormat deal with `InputStream` today. `InputStream` as an interface allows for blocking reads. That is the co-ordinator way of doing things. The Router deals with `ByteBuffers` as everything is non-blocking and goes out of its way today to create an `InputStream` today to deal with the protocol, or read from an `InputStream` into a `ByteBuffer` when dealing with MessageFormat.

We should get to this once the coordinator is replaced (or we will have to make the change in the coordinator as well).

EDIT:  Or `ReadableByteChannel` may be more appropriate. Since `ByteBuffer` has to allow for seeks and rewinds it might involve additional copies. `ReadableByteChannel` is more in line with `InputStream` (but non-blocking by definition).

**Comment by vgkholla** [comment]
@pnarayanan isn't this done?

**Comment by cgtz** [comment]
Now, our request/response objects are `ByteBuf` aware.
