### ISSUE TITLE
Add metrics for the NetworkClient

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#315]
`NetworkClient` does not have any metrics currently. This task involves going over the class and adding metrics wherever applicable. Some of the metrics required are:

 1. How long (histogram) a request remains in the `NetworkClient`'s queue before it gets sent out to the `Selector`.

 2. How long (histogram) it takes for a response to arrive for a request that was sent out via the `Selector`, if possible.

 3. Counts of established connections and such.

Additionally, note that previously `NetworkSend` was only used by the server to send responses. So the `NetworkRequestMetrics` within it are populated at the server and only includes metrics from the time the request arrives to the time the response is sent (basically request queuing time, send time and total time). Also, `NetworkRequestMetrics` assumes that `NetworkSend` objects are *always responses*. That needs to change.

I suggest the following approach:
1. Understand how `NetworkRequestMetrics` work. They are initialized with `ServerMetrics` histograms and the fields get updated along the way.
2. Add new fields as necessary to account for requests sent out from the `NetworkClient` and get rid of assumptions. This may involve renaming variables and methods or adding new variables.
3. Make `NetworkClient` initialize the `NetworkSend` metrics it creates appropriately (currently it initializes it with null).

It might also help taking a look at the `BlockingChannel` and `BlockingChannelPool` related metrics to see if there are anything relevant to pick up from there.

Acceptance Criteria:
- `NetworkSend` and `NetworkRequestMetrics` are made agnostic of whether the `Send` is a request or a response.
- `NetworkClient`, which now creates `NetworkSend` with a null `NetworkRequestMetrics` because of the above reason, is initialized appropriately with `NetworkClient` metrics.
- Other relevant `NetworkClient` metrics.

**Comment by nsivabalan** [comment]
Here is the patch : https://github.com/linkedin/ambry/pull/331
