### ISSUE TITLE
Handle chunk expiry and deletion during an ongoing query

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#323]
When getting chunks of a composite blob, if the metadata chunk is successfully retrieved (not deleted or expired), then the data chunks should be successfully retrieved no matter what - if not, it is an internal server error. That is, the router should never return `Blob_Deleted` or `Blob_Expired` for a data chunk.

However, the following can occur:
- the blob was not expired at the time the metadata chunk is fetched, but gets expired while the chunks are being fetched. This can cause a valid scenario where an intermediate chunk potentially returns a `Blob_Expired` error.
- the blob gets deleted after the metadata chunk (and possibly a few initial chunks) are returned for an  ongoing query. This can cause a valid scenario where an intermediate chunk potentially returns a `Blob_Deleted` error. 

Although ambry is eventually consistent, if the metadata chunk did not encounter an error, then the data chunks shouldn't either. In a way, we are talking about atomicity here (get all chunks or none at all).

Gopal and I discussed this and we think the right approach here is to include deleted and expired `GetOptions` when data chunks are fetched for a composite blob. Because if the `GetManager` is at a point where it initiates requests for data chunks, that means it has already fetched the metadata chunk successfully.

**Comment by vgkholla** [comment]
I think this can be newbie ? The description is well written, the acceptance criteria is clear, the change is simple and isolated.

**Comment by pnarayanan** [comment]
Technically, yes this is a newbie. However, I was intended to include the change as part of PR #308 when I created this issue (and I just made the change).

The main purpose of creating this issue was to document this scenario.

**Comment by pnarayanan** [comment]
This commit in that PR addresses the issue: https://github.com/linkedin/ambry/pull/308/commits/9f9b037a16f0d61af21827d6dc89bd973ebb467d

**Comment by pnarayanan** [comment]
Closing this, as PR #308 is merged.
