### ISSUE TITLE
Selector poll does not return explicitly closed connections

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#328]
If a connection is explicitly closed using the `close(connid)` method, then the closed connection immediately gets added to `disconnected` list. This list is cleared at the start of every `poll()`. This means that an explicitly closed connection will not be returned as part of disconnections after a poll. This is unintuitive and incorrect.

Instead, the selector should add these disconnections to a temporary list and use it to populate the `disconnected` list *during* a poll. Basically any additions to `connected`, `disconnected`, `completedSends` and `completedReceives` should happen as part of a poll.

**Comment by nsivabalan** [comment]
Pull request: https://github.com/linkedin/ambry/pull/351

**Comment by nsivabalan** [comment]
Closing the issue as the pull request has been merged.
