### ISSUE TITLE
Additional metrics for the NonBlockingRouter

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#330]
Should add metrics to get insight into:
- chunk filler thread performance (how well channel is getting read and chunks filled)
- request response handler thread performance (how long poll takes, response handling takes etc.)
- also need a way of tracking memory usage

**Comment by vgkholla** [comment]
@xiahome @pnarayanan Is this issue still relevant or have these metrics been added?

**Comment by pnarayanan** [comment]
This can be closed. There are no explicit metrics for tracking memory usage by the router, but that is unnecessary - jvm metrics are sufficient.
