### ISSUE TITLE
Handle exceptions within operation manager polls

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#333]
The operation manager poll can throw runtime exceptions, even due to faults in components outside of its own control (for example, due to faults in caller provided callbacks and channels). Currently any unhandled exception can shut down the `RequestResponseHandler`.

A similar issue exists with exceptions during chunk filling.

We don't need to overcomplicate things, but at the very least, the operation managers could catch these exceptions and continue by removing these faulty operations from its list, so that any such errors are isolated to only the operation that caused it.

**Comment by cgtz** [comment]
Fix for issue has been merged, closing issue
