### ISSUE TITLE
Add Router configurations to wiki

### ISSUE THREAD

**Issue by vgkholla** [linkedin/ambry#342]
Once Router configurations are finalized, please add them to the wiki [here](https://github.com/linkedin/ambry/wiki/Frontend%20Configuration).

**Comment by vgkholla** [comment]
@pnarayanan Is it possible to do this now that the Router is ready?

**Comment by vgkholla** [comment]
@pnarayanan - can this be done?

**Comment by pnarayanan** [comment]
Updated, closing.
