### ISSUE TITLE
Fix the buffer size allocated in PutRequest

### ISSUE THREAD

**Issue by nsivabalan** [linkedin/ambry#350]
PutRequest allocates a buffer of header/metadata size (entire size - blob content size) and then re-uses the same buffer to send the actual blob content as well. This is causing some performance problems and Ming also saw a significant improvement in his perf test results locally. 

Fix suggested:
Ideally we were thinking of making a fix to have a buffer size same as socket buffer size. But then, we are making 3 copies of the data as of now in three different places. 1: At the coordinator or router layer. 2: At the PutRequest layer just before writing the data to the channel/network. 3: For ssl connections, we need to encrypt the data and hence one more copy in SSLTransmission. 

So, we could change the signature of PutRequest to take in ByteBuffer rather than InputStream and hence avoid the 2nd copy altogether. But this fix has to wait until coordinator is phased out.

**Comment by pnarayanan** [comment]
Fixed in #445
