### ISSUE TITLE
Setting netty.server.so.backlog in frontent.properties

### ISSUE THREAD

**Issue by mtolman** [linkedin/ambry#355]
Hi - When I try to set "netty.server.so.backlog" to a higher number in the frontend.properties config file, I get this warning:

[2016-06-14 15:07:35,502] WARN Property netty.server.so.backlog is not valid (com.github.ambry.config.VerifiableProperties)

I believe it is because this line has a typo -- "sobacklog" instead of "so.backlog":

https://github.com/linkedin/ambry/blob/master/ambry-api/src/main/java/com.github.ambry/config/NettyConfig.java#L60

**Comment by vgkholla** [comment]
Thanks for catching this ! Have put up #356 to fix this - should get merged soon.

**Comment by vgkholla** [comment]
#356 is merged - so this should be fixed. I'll close the issue but please verify !
