### ISSUE TITLE
IllegalArgumentException in SimpleOperationTracker closes router.

### ISSUE THREAD

**Issue by xiahome** [linkedin/ambry#360]
In `SimpleOperationTracker`, if replicas.size() is less than successTarget, an `IllegalArgumentException` will be thrown. This exception however will eventually close the router, but this exception should not be at that serious level. Reporting this issue to seek a reasonable solution.

**Comment by vgkholla** [comment]
I think #354 should be able to handle this. Can you confirm with @cgtz ?

**Comment by cgtz** [comment]
I checked through all of the places where `SimpleOperationTracker`s are instantiated. For Put/Get, the trackers are instantiated in the handleResponse/poll methods, where an unexpected exception will just end the operation.  However, for GetBlobInfo/Delete, this is called in the submit method, which only catches `RouterException`s right now.

**Comment by pnarayanan** [comment]
I disagree with the premise. Why should this be handled anyway? If the number of replicas is less than `successTarget`, what is the value in keeping the router running? Subsequent operations are going to fail as well. We should simply bail out so that the administrator can fix the configs and redeploy.

**Comment by xiahome** [comment]
Could this condition happen in failure scenario and becomes normal later? Another point worth thinking is, this could fail only one type of operation, but remaining may still be working. So should we let the router be shut down sacrificing all operations, or we got notification for this exception (if it is captured) and make a further decision?

**Comment by pnarayanan** [comment]
Let me also point out that the idea with #354 is to prevent a single "bad" operation from bringing down the router. This, on the other hand, is not an error at the operation level, but at the router level (bad router configs).

**Comment by xiahome** [comment]
I think the conclusion is that this error should not be captured as the misconfiguration is at the router-level. Partially working does not warrant continuation of the router. I am closing this issue since no concrete work is needed for this.
