### ISSUE TITLE
REST-Level Authentication/Security

### ISSUE THREAD

**Issue by mtolman** [linkedin/ambry#365]
In the Introduction to Ambry blog [article](https://engineering.linkedin.com/blog/2016/05/introducing-and-open-sourcing-ambry---linkedins-new-distributed-), it talks about adding authentication and security support to the REST API. Has any support been added for this already, or is still on the todo list?

Thanks,
Mike

**Comment by nsivabalan** [comment]
No @mtolman. We don't have any support for REST-Level authentication/security for now. Its on todo list for now.

**Comment by sriramsub** [comment]
We will be happy if you can start a design discussion around it if you
would like to.

**Comment by mtolman** [comment]
Thanks. I'm mainly wanting to restrict GET and DELETE operations to a few IP addresses, while allowing POST from many (or possibly all) IP addresses. Does that kind of support exist, or do you have any suggestions on how to do that?

**Comment by vgkholla** [comment]
@mtolman This should be possible by writing your own implementation of `SecurityService` that `AmbryBlobStorageService` can use. The default `AmbrySecurityService` does nothing and is a no-op.

**Comment by vgkholla** [comment]
Once you have your implementation and a factory, you can simply change configs to use your custom implementation (`frontend.security.service.factory`)

**Comment by mtolman** [comment]
Thanks! I will give this a try. If it works out well, I'll post back the custom implementation.

**Comment by vgkholla** [comment]
Ambry now supports SSL. This particular task can be done by either having a custom impl of `SecurityService` or by setting up key and trust stores appropriately.
