### ISSUE TITLE
Question about Deletion/Compaction

### ISSUE THREAD

**Issue by mtolman** [linkedin/ambry#373]
Hi,

From what I've read in the wiki, Ambry zeroes-out deleted blobs on the disk after a deletion occurs, but it is unclear to me what happens with the deleted blobs. The wiki mentions that Compaction isn't currently supported. Does Ambry currently do anything with the deleted blob space, or is that deleted space simply not available after a delete happens?  Based on my testing, it appears that the log size continues to grow regardless if there is deleted space.

Thanks again,
Mike

**Comment by pnarayanan** [comment]
Hey Mike,
We are working on compaction. For now, deleting a blob will not save storage space.
There is a feature (hard deletes) that asynchronously runs on the partitions and zeroes out blobs (sets each byte of the blobs to 0) that are deleted and are outside of a retention window. This is useful to meet privacy requirements (if any) with storing user data.

**Comment by mtolman** [comment]
Thanks. I appreciate the quick reply.

**Comment by heipacker** [comment]
What is the progress of the compression feature development?
