### ISSUE TITLE
Cloud services

### ISSUE THREAD

**Issue by drewpotter** [linkedin/ambry#388]
Hi,

Thanks for releasing this awesome code.

I just wanted to know whether it was possible (or totally unnecessary and missing the point?) to combine LinkedIn's Ambry with something like Amazon S3. 

Or in other words, the use of Ambry on top of Amazon cloud services and whether this makes sense or not? 

Thanks

Andrew

**Comment by vgkholla** [comment]
Hey Andrew,

From the information you provided, it seems like it would not make sense since Ambry is an object storage system by itself. Could you elaborate the use case where you think this might make sense?

Gopal

**Comment by drewpotter** [comment]
Basically I am developing a web App and want to be able to run it on AWS but also to run it on my own server where I will use Ambry. So my backend will need to be able to work with either AWS or Ambry.

You are right, where would this make sense? I guess on AWS there is no point using Ambry as Amazon provides their own version of the same thing. However, on my own server I would really like to use Ambry.

Thanks,

Andrew

**Comment by vgkholla** [comment]
Yeah - Ambry in conjunction with AWS does not make sense. If your intent is to use AWS or Ambry based on environment (i.e. PROD vs local deployment), my suggestion would be to make your app work both with Ambry and AWS and switch b/w them based on environment. If you use the simplest APIs that both these systems provide (put, get, delete), this should be possible.

**Comment by drewpotter** [comment]
Thanks for that. I will intend to do this.
