### ISSUE TITLE
Fixes to quickstart documentation

### ISSUE THREAD

**Issue by vgkholla** [linkedin/ambry#395]
Minor fixes to quick start doc
1) Mention that the minimum java version supported is 1.7
2) Provide http link for the github repository instead of the "git@github" link.

Make same changes in README.

**Comment by pnarayanan** [comment]
and make sure the default port in the examples are correct (should probably be 15158 now?)

**Comment by vgkholla** [comment]
The default is still 1174 so I don't think that change is required.

**Comment by vgkholla** [comment]
Thanks for fixing this @nareshbafna
