### ISSUE TITLE
Investigate and document Pros and Cons of compaction design w/ and w/o log segments

### ISSUE THREAD

**Issue by nsivabalan** [linkedin/ambry#399]
Compaction on a high level can be designed with or w/o log segments. W/o log segments mean, a replica consisting of one big log file. W/ log segments mean, a replica consisting of N number of log segments.

Before diving deep into any other system for compaction design, on a high level we need to decide if need log segments or not. If not for this, we can't go ahead with the design. So, first step is the document the pros and cons for designing compaction w/ and w/o log segments.

We also need to consider what is the pros and cons of having log segments for ambry (store) in general and not just from compaction perspective.

AC:
Publish a document that speaks about pros and cons of having log segments vs not.
Get feedback from others
Narrow down to either one of the them

**Comment by sriramsub** [comment]
is it even an option to not have segments? It is impossible to compact a 100gb file online without segment support.

**Comment by nsivabalan** [comment]
not online though. This idea was floating around. So thought lets document and investigate about it. 

Something like, once any log/replica has 30% of its content deleted, we can mark it as read_only, do compaction and revert it back to read_write sort of. Again, this is a very high level idea. Lot more details have to figured out. We are just thinking at a high level, whether to have log segments or not.

**Comment by sriramsub** [comment]
Yeah, not sure how that will work. You eventually have to compact the whole log as it grows.

**Comment by nsivabalan** [comment]
Compiled the pros and cons for different approaches here:
https://drive.google.com/file/d/0BxchCf98eckGcEo2RkZBSVBLeTg/view?usp=sharing

**Comment by vgkholla** [comment]
@sriramsub Could you elaborate why you think it would be impossible to compact the log file as a whole? Ignoring the triggers (which can vary based on the size the log file has reached etc), what could be the problem with doing the compaction itself?

At a high level, this would involve copying all the data (while the partition is still "live") and then doing iterative copying until there is only a few new records that need to be copied. At this point, take a software lock, finish the copying and replace the old non compacted store with the new compacted store. The time to do this will be short. The idea is very similar to how live VMs are migrated.

What do you think the possible problems might be?

Also, I have updated the document with more details and some experiments that we did. Would be awesome if you could take a look.

**Comment by sriramsub** [comment]
1. You have to keep your partitions to a very small size or have a large swap space
2. You would block both read and write. It seems like the lock is instant but that has massive impact in dropping your writes to 0 which is never good for a storage system.

**Comment by vgkholla** [comment]
Point 1 - this is true and is noted in the pros and cons. 
There are some workarounds by using symlinks, the caveat here being that it introduces a bit of an operations overhead; but the partition size limit is something that looks like it can be dodged.

Point 2 - If compaction is the rare event that it is envisioned to be and happens on, say, a single partition per disk at a time (or even lesser), would this be so bad? Also, I haven't given this deep thought but it might be possible to avoid "dropping"  reads/writes. I was thinking more in terms of "delaying" them while the switch occurs.

**Comment by vgkholla** [comment]
Based on the documentation provided and discussions, we decided to go with the segmented log approach owing to the fact that
1. The segmentation approach places no artificial caps on possible partition sizes.
2. It allows configurable swap space sizes.
3. Possibly avoids unnecessary extra I/O.

The implementation details of the segmentation are a little more involved than the non-segmentation approach but the core problems to solve remain the same. The segmentation approach just requires a bit more "book-keeping".
