### ISSUE TITLE
Implement range request support

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#412]
To support video playback and storage in Ambry, we need to support range requests, that is, retrieving a specific byte range from an object. Media players require this feature so that they don’t have to retrieve an entire video file to play it back.

**Comment by cgtz** [comment]
See (and comment on) the following in-progress design document on this feature:
https://docs.google.com/document/d/1AJ5NZD_mH6ve6EYsrs8UPsEAo2jgLvDNAJb1lWQUSsU/edit?usp=sharing

**Comment by vgkholla** [comment]
@cgtz can this be closed?
