### ISSUE TITLE
Remove ambry-coordinator

### ISSUE THREAD

**Issue by vgkholla** [linkedin/ambry#432]
Since the `NonBlockingRouter` is ready, the `Coordinator` can be removed.

**Comment by vgkholla** [comment]
The major roadblocks to removing the `Coordinator` is the fact that it is used in server tests and ambry-tools. Once these usages are removed, it should be easy to remove the `Coordinator`. There will be no more production code usage of `Coordinator` after #431 is closed.

**Comment by pnarayanan** [comment]
Also identify what related classes can be removed and then remove them. Some of them (like `BlockingChannel`) will still need to be around for replication.

**Comment by sriramsub** [comment]
This is awesome!
