### ISSUE TITLE
Add router interface for getting blob info and blob data in a single call.

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#436]
To avoid an extra round trip to get the blob info during a get request, we can add support for using the getBlobAll server API within the router. This means that blob properties, user metadata, and blob data will all be returned in the same request. 

For the interface we have a couple of options:

#### Option 1
- Have `router.getBlob(...)` return a `GetBlobResult` object that can either contain the `ReadableStreamChannel`, or the `ReadableStreamChannel` and `BlobInfo`.
- Add a new option to `GetBlobOptions` that allows the user to either get `BlobInfo` and the `ReadableStreamChannel`, or just the `ReadableStreamChannel`.
- Keep the existing `router.getBlobInfo(...)` method for getting just the `BlobInfo`

#### Option 2
- Have `router.getBlob(...)` return a `GetBlobResult` object that can contain just the `ReadableStreamChannel`, just the `BlobInfo`, or the `ReadableStreamChannel` and `BlobInfo`.
- Add a new option to `GetBlobOptions` that allows the user to get `BlobInfo` and the `ReadableStreamChannel`, just the `BlobInfo`, or just the `ReadableStreamChannel`.
- Remove the existing `Router.getBlobInfo(...)` method for getting just the `BlobInfo`, and have the user call `router.getBlob(...)` with the correct option set to get only the `BlobInfo`

This would require some additional changes to combine the functionality in `GetBlobInfoOperation` and `GetBlobOperation` but could potentially help in terms of code cleanliness. I want to get others' opinions on this.

**Comment by vgkholla** [comment]
I vote for option 2

**Comment by pnarayanan** [comment]
Basically, the api should now allow getting just the BlobInfo, just the Blob, or both BlobInfo and the Blob - as we concluded that there are possible use cases for all three. 
Option 1 is a bit asymmetrical. With this new requirement, we should either go with 3 different calls (getBlobInfo()/getBlob()/getBlobAll()) or go for Option 2 (one call with options to distinguish the three cases).
Option 2 lets keep the api lean, and I find it more natural.
