### ISSUE TITLE
Investigate and possibly implement combining getBlobInfoOperation and getBlobOperation classes

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#443]
Currently they are two different classes. Now that the distinction between the two operations are blurred (it is done via options and not separate calls), perhaps combining the two would be cleaner, and we can get rid of the `GetOperation` abstract class as well. This issue is to investigate and possibly implement that.

**Comment by vgkholla** [comment]
Dependent on the merge of #439

**Comment by pnarayanan** [comment]
I looked into this and I think it is difficult and not a good idea to combine these two classes - although the two cases seem similar, there is an inherent difference between getting just the `BlobInfo` and getting the `BlobInfo` as part of getting both `BlobInfo` and the `Data`. For the latter, the first chunk is always fetched and the `BlobInfo` is simply separated out during deserialization - the point being that the latter is not necessarily a "superset" of the former and as such keeping the two separate seems like the right thing. 

Combining the classes would makes things a bit messier as well as there is an asymmetry between `GetBlobOperation` and `GetBlobInfoOperation` in that a lot of work (including request creations and response interpretation) is done by a `GetChunk` in the case of the former. For just the `BlobInfo`, there are no chunks involved and everything is done within the operation itself.
