### ISSUE TITLE
Puts occasionally get Blob_Exists error due to fast replication

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#454]
Put operations today make parallel requests to _N_ number of data nodes in the synchronous path (where _N_ is the request parallelism) and relies on async replication to ensure that all replicas eventually get the blob. However, given two datanodes D1 and D2, if the request from the frontend reaches and completes successfully in D1, and D1 happens to replicate to D2 faster than the request from the frontend reaching D2, then the request (and possibly the overall operation itself) fails due to a _Blob_Already_Exists_ error.

Currently this is mitigated to an extent due to a hack that delays replication within the local DC if it has already caught up. Even then the problem occasionally shows up.

We should:
- come up with a better solution to deal with this and distinguish between an actual blob id collision and the case described above.
- once that fix is in, we should get rid of the above hack.

**Comment by vgkholla** [comment]
You could also add your suggestion for the solution - I think it is a useful starting point.

**Comment by nsivabalan** [comment]
My suggestion: Incase we could come up with a SLA for replication to catch up for any blob, then we could have a solution as follows:
On encountering a put request for a blob that was created within the SLA, we can return success. If not, we can return Blob_Already_Exists error.

**Comment by vgkholla** [comment]
I think there are multiple problems with that approach:
1. Coming up with the SLA.
2. Two corner cases
   a. Valid blob put comes after the SLA expires - you would have the same problem we have now i.e. a spurious failure. The solution just mitigates this problem and doesn't solve it. In that way it isn't much different from what we have now
  b. Actual collision arrives within the SLA. This is the bigger problem and Ambry would return success when it should not have.

@pnarayanan had something built on top of #455 in mind and I think that has the possibility of being a deterministic and correct solution.

**Comment by pnarayanan** [comment]
A proposed fix we discussed is the following: 
The thing we need is a way to distinguish between actual key collisions and the case where replication request arrives and succeeds sooner than the arrival of the put request. One way to achieve this is by making use of the journal to determine whether the blob for which this error is received is recent. Additionally, as @vgkholla noted above, if it is indeed recent, we still need to confirm that there is no real collision. To do that, we can include CRCs in the blob put requests (#455) and keep them in the journal and compare the CRCs to determine whether there was an actual collision. If it is determined that the two blobs are the same, then the datanode can safely return a _No_Error_.
