### ISSUE TITLE
Windows set up

### ISSUE THREAD

**Issue by ckharide** [linkedin/ambry#463]
Hi there ,

I have a windows set up working with two batch files in bin/windows that i have developed called ambry-front-end.bat and ambry-server.bat in my local git branch which starts the front end server and the ambry server on windows .  Now i need to merge the changes from the remote into the branch but while doing it gives me an error indicating remote is not found . Apologies but am new to git , would like to know how can pull out the remote changes into my branch/master. 

$ git remote -v
origin  https://github.com/ckharide/ambry (fetch)
origin  https://github.com/ckharide/ambry (push)
upstream        https://git@github.com:linkedin/ambry.git (fetch)
upstream        https://git@github.com:linkedin/ambry.git (push)

$ git fetch upstream
fatal: repository 'https://git@github.com:linkedin/ambry.git/' not found

~Chandra.

**Comment by vgkholla** [comment]
@ckharide the upstream you have set is invalid. Set it as either "git@github.com:linkedin/ambry.git" or "https://github.com/linkedin/ambry.git" and it should work

**Comment by ckharide** [comment]
Ah thanks .. Sorry for the trouble.
