### ISSUE TITLE
Router should not depend on the size in blob properties for puts

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#479]
This is required to support callers that do not know the length of the data being put in advance.

This actually needs a bit of work in the router. Since the size was readily available before, it used this information to help determine a few things in advance, such as whether the object is going to be composite or not, how big the metadata chunk array should be, and so on.

The router does not have to depend on this though, as the metadata chunk is only put at the end and that is the only chunk into which the BlobProperties (with a valid size) needs to go.

**Comment by vgkholla** [comment]
Being fixed in #540 

@pnarayanan: Please close when this is done.
