### ISSUE TITLE
Swithing to VERSION_2 for StoreFindToken

### ISSUE THREAD

**Issue by nsivabalan** [linkedin/ambry#522]
There is a new version of StoreFindToken which contains inclusiveness and incarnationId. We already have a [patch in progress](https://github.com/linkedin/ambry/pull/511) that introduces this new version but supports it only in read path. 

when switching to VERSION_2:
1. Change StoreFindToken.getBytes() to include incarnationId and inclusiveness flag
2. Add tests in serDeTest of StoreFindTokenTest to test the incarnationId and inclusiveness flag.

**Comment by vgkholla** [comment]
Done in #534
