### ISSUE TITLE
Ensure Replication continues in the event of compaction

### ISSUE THREAD

**Issue by nsivabalan** [linkedin/ambry#538]
Replication uses StoreTokens to make progress. But during compaction the store tokens might become invalid since log segments and index segments might be compacted to new ones. So, we need a fix to ensure replication progresses smoothly in the event of compaction. 

Here is the design [doc](https://docs.google.com/document/d/1Lg2Alp5jPfD9NkvDExi0LuLKuurRllV6l3s2-D5YCLg/edit#heading=h.xf8aboc9a136) detailing the fix. 

Basically, a new Reset Key is introduced in every Index Segment which will be pointing to the first key in the log segment along with its type(Put/Delete) that the index segment refers to. It is also returned as part of theStoreFindToken. If the Offset(name + storeKey) that the storeToken is referring to becomes invalid (due to compaction) during a findEntriesSince() call, the store token is reset to the index segment containing the reset key from the storetoken and entries starting from that offset is returned.

**Comment by vgkholla** [comment]
@nsivabalan there is already an issue that I have created a while ago for this -> #430. Could you add your comments there and close this issue? thanks.

**Comment by nsivabalan** [comment]
Closing this issue as its a duplicate
