### ISSUE TITLE
free deleted space support

### ISSUE THREAD

**Issue by iwangheng** [linkedin/ambry#675]
the space of deleted file should be freed when partition no space。
1、set the partition to readonly
2、offline some copy
3、free space and onlie
4、repeat 2、3
5、set writeable

**Comment by vgkholla** [comment]
@iwangheng Could you elaborate Step 3 - "free space"? How are you freeing space?

**Comment by iwangheng** [comment]
move the files between two deleted file forward，make the normal files contiguous，regenerate the index file。

**Comment by vgkholla** [comment]
@iwangheng compaction should cover this use-case. Please reopen if it does not

https://github.com/linkedin/ambry/wiki/Compaction
