### ISSUE TITLE
PartitionManager not working

### ISSUE THREAD

**Issue by ohze** [linkedin/ambry#692]
I've just updated the [Basic Operations](wiki/Basic%20Operations) page:
The main class is `com.github.ambry.clustermap.PartitionManager` instead of `com.github.ambry.tools.admin.PartitionManager`.

But I found PartitionManager is not working as expected:
```bash
git clone git@github.com:linkedin/ambry.git
cd ambry
./gradlew allJar
java -cp target/ambry.jar com.github.ambry.clustermap.PartitionManager \
    --hardwareLayoutPath config/HardwareLayout.json \
    --partitionLayoutPath config/PartitionLayout.json \
    --operationType AddPartition \
    --numberOfPartitionsToAdd 5 \
    --numberOfReplicasPerDatacenter 3 \
    --replicaCapacityInBytes 107374182400
```
=> error:
```
Error while executing partition command java.lang.IllegalArgumentException: Missing required property 'clustermap.cluster.name'
```

**Comment by ohze** [comment]
When I change class `PartitionManager` as [this](https://github.com/linkedin/ambry/compare/master...ohze:issues/692) then run:
```bash
java -cp target/ambry.jar com.github.ambry.clustermap.PartitionManager \
    --hardwareLayoutPath config/HardwareLayout.json \
    --partitionLayoutPath PartitionLayout.json \
    --operationType AddPartition \
    --numberOfPartitionsToAdd 5 \
    --numberOfReplicasPerDatacenter 3 \
    --replicaCapacityInBytes 107374182400
```
_note: `--partitionLayoutPath` is not exists_
Then `PartitionLayout.json` is created with the following content:
```json
{
  "clusterName": "OneDiskOneReplica",
  "partitions": [],
  "version": 1
}
```
Is this the expected result?

**Comment by vgkholla** [comment]
@cgtz @pnarayanan

**Comment by cgtz** [comment]
@ohze It seems that this CLI tool did not keep up with new required properties. The second result seems to be expected, since the HardwareLayout chosen does not have enough space for a partition of size 107374182400 (only one disc of size 21474836480 is in the HW layout file).

**Comment by johnnyjian** [comment]
I have tried to fix this by adding the serverPropsFilePath option, see #914
