### ISSUE TITLE
[question] Stable state of master branch and "helix" feature?

### ISSUE THREAD

**Issue by ohze** [linkedin/ambry#699]
1. Can we using ambry in production environment by compiling from source in `master` branch? (is `master` branch supposed to be stable?)
2. Similar question for using ambry with Helix.
We are running ambry + Helix on [Rancher](http://rancher.com/rancher/) in own test environment and it's good so far.

**Comment by vgkholla** [comment]
Hello @ohze - Ambry's master branch is stable to use. However, if you find any critical bugs, please report them and we will fix them quickly.

Ambry with helix is also stable to use. If you have specific questions (or bugs), you can reach out to @pnarayanan.
