### ISSUE TITLE
Mark partitions as read-only (and read-write) dynamically

### ISSUE THREAD

**Issue by vgkholla** [linkedin/ambry#737]
With the introduction of the `HelixClusterManger` and its support to mark partitions as RO, it should be possible to mark the local replica of a partition as RO (which results in the partition becoming RO) when the `BlobStore` reaches a preconfigured percentage of its capacity.

Similarly, if the `BlobStore` were to dip below the configured percentage (for e.g. because of regularly scheduled compaction), it should mark its replica as RW (the partition will become RW if all the replicas mark themselves RW).

**Comment by pnarayanan** [comment]
[This](https://docs.google.com/document/d/1gMweKKzpgcGciXzhNpjI3gf9973QhkZoYA6YkUhaFvU/edit#heading=h.2jxsxqh) section in the Helix cluster manager design specifically talks about how partitions are marked as RO (sealed) and brought back to RW state. 

Helix cluster manager already treats a partition as RO if any of its replicas are RO and treats a partition as RW only if all of its replicas are RW.

What is left is for the store to determine when the associated replica should be RO or RW and to update this in Helix via the participant.

**Comment by vgkholla** [comment]
To achieve this, the store needs to tell the cluster map about the events.

On the put and delete path in `BlobStore‘, the fill level has to be checked against a configured fill level at which the store should be marked RO. If the fill level is beyond this number, the store should tell the cluster manager about it. 

For the reverse, compaction is the only thing that can reduce store size. So once compaction is finished, the fill level has to be checked. If the fill level is below the config (plus some more to prevent flapping), then the cluster manager has to be told about it. 

The store has no access to the cluster map (and perhaps should not). So a callback class has to be introduced that can be passed to the stores that allows them to call into methods when conditions are met. 

Another case is to handle is recreation. If a replica has been marked RO, if it is recreated (or it is discovered on startup that the fill level is not enough), then the cluster manager has to be told about it 

This should cover all cases

**Comment by vgkholla** [comment]
Please add if I have left any out @pnarayanan

**Comment by dharju** [comment]
@vgkholla @pnarayanan what would be a good size threshold for a default value?

**Comment by vgkholla** [comment]
@dharju As discussed, this depends on the average blob size and the ratio of deletes/puts. Let's fix the default at 95 and since we are making this a configuration, it can be finetuned later

**Comment by vgkholla** [comment]
Finished as a part of #779
