### ISSUE TITLE
Config for HelixAccountService.

### ISSUE THREAD

**Issue by xiahome** [linkedin/ambry#756]
Currently configs in for `HelixAccountService` is in `HelixPropertyStoreConfig`, because both `HelixNotifier` and `HelixAccountService` are using these configs. However, this makes some other configs that solely belong to `HelixAccountService` also be placed in `HelixPropertyStoreConfig`, such as shutdownTimeout for shutting down `HelixAccountService`. This ticket proposes to move `HelixAccountService`-related configs to `HelixAccountServiceConfig`.

**Comment by cgtz** [comment]
Fixed by #818
