### ISSUE TITLE
Providing service ID is mandatory even when account and container specified

### ISSUE THREAD

**Issue by siepkes** [linkedin/ambry#799]
I don't know if it was intentional but since a couple of days (don't exactly know which commit introduced this behavior) it is mandatory again to supply the `x-ambry-service-id` even though the `x-ambry-target-account-name` and `x-ambry-target-container-name` are supplied.

Some superficial debugging by me revealed that the `AccountAndContainerInjector#injectAccountAndContainerForPostRequest` method threats the request as expected; If the account and container are specified the service id is not required. Things go awry in the `RestUtils#buildBlobProperties` method which has a line mandating the service id no matter what or an exception is thrown:

```
String serviceId = getHeader(args, Headers.SERVICE_ID, true);
```

**Comment by vgkholla** [comment]
@siepkes the code in `RestUtils#buildBlobProperties` has not changed and it has always demanded that the serviceId be present IIRC. There are quite a few places in code where `blobProperties.getServiceId()` is assumed to be non-null I think

**Comment by siepkes** [comment]
@vgkholla Oh, I thought I recalled I could make requests without a service id but maybe i'm mixing things up. In any case its clear to me now, thanks for the insights! Do you want to leave this issue open (ie. is it a goal for you guys to be able to work without the service id)? Or should I close it?

**Comment by vgkholla** [comment]
@siepkes we currently don't have plans to retire the service ID. So I will close this issue.
