### ISSUE TITLE
use ambry in production env

### ISSUE THREAD

**Issue by gmxus** [linkedin/ambry#809]
Which version of the ambry is in use at linkedin?

**Comment by vgkholla** [comment]
@gmxus Are you considering deploying it for your use and are interested in a recommendation? We like to use the latest, but it’s also a function of business requirements

**Comment by gmxus** [comment]
We decide to use ambry in production, stability is more important than features for us

**Comment by siepkes** [comment]
@gmxus We (we are not affiliated with LinkedIn except that I have an LinkedIn account :smile: ) run Ambry in production and use pretty much the latest version. Ambry has a lot of (unit) tests to prevent regressions in newer version. We usually take a commit hash, build a version from it and do some light testing on it before we deploy it to our production environment.

It would be quite easy to create a branch of a commit which you maintain as stable version (ie. only apply security and bugfixes).
