### ISSUE TITLE
MIN_DISK_CAPACITY_IN_BYTES at 10 GB

### ISSUE THREAD

**Issue by silvanheller** [linkedin/ambry#826]
Is there a reason why the min disk capacity (clustermap.ClusterMapUtils) is 10GB and not something lower, e.g. 10MB? My use case is a dockerized testing/integration setup and I think allocating 10 GB of storage is prohibitively high for simply testing an ambry deployment.

**Comment by pnarayanan** [comment]
These may be tied to the defaults used for log segment sizes, which are probably in GBs. Plus, the disk has to store other metadata like index segments, replica tokens, hard delete tokens etc. So 10MB may be a bit low. You could try changing that and see where that leads you.
