### ISSUE TITLE
Change Disk_Unavailable to a new type of ServerErrorCode when a store is stopped

### ISSUE THREAD

**Issue by jsjtzyy** [linkedin/ambry#900]
Use a more accurate ServerErrorCode (like Partition_Unavailable) instead of Disk_Unavailable to indicate a particular store is unavailable. This is necessary when a store is stopped however the disk hardware is still up. The requests for other stores should be approved in validateRequest method.
#884

**Comment by pnarayanan** [comment]
While fixing this, we should also introduce an `isAvailable()` method to `ReplicaId` interface, because previously availability applied at node and disk granularity, now it applies to individual replicas as well.

**Comment by jsjtzyy** [comment]
The issue is fixed in #988
