### ISSUE TITLE
MessageFormatInputStream does not conform with InputStream

### ISSUE THREAD

**Issue by dharju** [linkedin/ambry#932]
"If len is zero, then no bytes are read and 0 is returned; otherwise, there is an attempt to read at least one byte. If no byte is available because the stream is at end of file, the value -1 is returned; otherwise, at least one byte is read and stored into b."  from `public int read(byte[] b, int off, int len) throws IOException` at https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html

`MessageFormatInputStream`'s `int read(byte[] b, int off, int len)` does not conform to this description, as it never returns -1.

**Comment by pnarayanan** [comment]
Other `InputStream` implementations in our code seems to have similar bugs. See @vgkholla's comment here about `MessageReadSetIndexInputStream` class: https://github.com/linkedin/ambry/pull/931/files/615da4866ecc9ed10c4cec955680e2eb8f4de308#r190741183

**Comment by pnarayanan** [comment]
`ByteBufferInputStream` implementation has (at least) one bug as well. `read(byte[] bytes, int offset, int length)` returns -1 if the argument `length` is 0, which is against the contract (which says that if length is 0, `read()` should return 0).
